import type { AttendanceRecord, Department, Employee, PayHistoryEntry } from './types'
import { getUKNow, getUKToday } from './uk'

export const MOCK_DEPARTMENTS: Department[] = [
  { _id: 'dept-1', name: 'Management', slug: 'management', color: '#1a6fd4', isActive: true },
  { _id: 'dept-2', name: 'Mechanics', slug: 'mechanics', color: '#059669', isActive: true },
  { _id: 'dept-3', name: 'Marketing', slug: 'marketing', color: '#d97706', isActive: true },
  { _id: 'dept-4', name: 'Sales', slug: 'sales', color: '#7c3aed', isActive: true },
  { _id: 'dept-5', name: 'Admin', slug: 'admin', color: '#64748b', isActive: true },
]

export const MOCK_EMPLOYEES: Employee[] = [
  {
    _id: 'emp-001',
    employeeId: 'AG-001',
    firstName: 'James',
    lastName: 'Harrison',
    email: 'j.harrison@asahigroup.co.uk',
    department: MOCK_DEPARTMENTS[0],
    jobTitle: 'Dealership Manager',
    phone: '07700 900001',
    startDate: '2018-03-15',
    employmentType: 'full_time',
    paymentMethod: 'monthly',
    payRate: 4500,
    payHistory: [
      {
        payRate: 4500,
        paymentMethod: 'monthly',
        employmentType: 'full_time',
        effectiveFrom: '2018-03-15',
        changedAt: '2018-03-15T09:00:00.000Z',
        note: 'Initial pay on registration',
      },
    ] satisfies PayHistoryEntry[],
    isActive: true,
  },
  {
    _id: 'emp-002',
    employeeId: 'AG-002',
    firstName: 'Sarah',
    lastName: 'Mitchell',
    email: 's.mitchell@asahigroup.co.uk',
    department: MOCK_DEPARTMENTS[1],
    jobTitle: 'Senior Technician',
    phone: '07700 900002',
    startDate: '2019-06-01',
    employmentType: 'full_time',
    paymentMethod: 'hourly',
    payRate: 18.5,
    payHistory: [
      {
        payRate: 17,
        paymentMethod: 'hourly',
        employmentType: 'full_time',
        effectiveFrom: '2019-06-01',
        changedAt: '2019-06-01T09:00:00.000Z',
        note: 'Initial pay on registration',
      },
      {
        payRate: 18.5,
        paymentMethod: 'hourly',
        employmentType: 'full_time',
        effectiveFrom: '2024-04-01',
        changedAt: '2024-03-28T10:00:00.000Z',
        note: 'Annual pay review',
      },
    ] satisfies PayHistoryEntry[],
    isActive: true,
  },
  {
    _id: 'emp-003',
    employeeId: 'AG-003',
    firstName: 'Tom',
    lastName: 'Morris',
    email: 't.morris@asahigroup.co.uk',
    department: MOCK_DEPARTMENTS[2],
    jobTitle: 'Marketing Executive',
    phone: '07700 900003',
    startDate: '2020-09-10',
    employmentType: 'part_time',
    paymentMethod: 'hourly',
    payRate: 15,
    hoursPerWeek: 20,
    isActive: true,
  },
  {
    _id: 'emp-004',
    employeeId: 'AG-004',
    firstName: 'Emma',
    lastName: 'Clarke',
    email: 'e.clarke@asahigroup.co.uk',
    department: MOCK_DEPARTMENTS[3],
    jobTitle: 'Sales Consultant',
    phone: '07700 900004',
    startDate: '2021-01-20',
    employmentType: 'full_time',
    paymentMethod: 'daily',
    payRate: 120,
    isActive: true,
  },
  {
    _id: 'emp-005',
    employeeId: 'AG-005',
    firstName: 'David',
    lastName: 'Wright',
    email: 'd.wright@asahigroup.co.uk',
    department: MOCK_DEPARTMENTS[1],
    jobTitle: 'MOT Tester',
    phone: '07700 900005',
    startDate: '2017-11-05',
    employmentType: 'full_time',
    paymentMethod: 'hourly',
    payRate: 17,
    isActive: true,
  },
  {
    _id: 'emp-006',
    employeeId: 'AG-006',
    firstName: 'Rachel',
    lastName: 'Bennett',
    email: 'r.bennett@asahigroup.co.uk',
    department: MOCK_DEPARTMENTS[4],
    jobTitle: 'Office Administrator',
    phone: '07700 900006',
    startDate: '2022-04-12',
    employmentType: 'part_time',
    paymentMethod: 'monthly',
    payRate: 2200,
    hoursPerWeek: 25,
    isActive: true,
  },
]

const today = getUKToday()
const now = getUKNow()

export const MOCK_ATTENDANCE: AttendanceRecord[] = [
  {
    _id: 'att-001',
    employee: MOCK_EMPLOYEES[0],
    signInTime: new Date(new Date(now).setHours(8, 15, 0)).toISOString(),
    status: 'signed_in',
    date: today,
    signInLocation: {
      latitude: 51.5074,
      longitude: -0.1278,
      accuracy: 12,
      capturedAt: new Date(new Date(now).setHours(8, 15, 0)).toISOString(),
    },
  },
  {
    _id: 'att-002',
    employee: MOCK_EMPLOYEES[1],
    signInTime: new Date(new Date(now).setHours(7, 45, 0)).toISOString(),
    status: 'signed_in',
    date: today,
  },
  {
    _id: 'att-003',
    employee: MOCK_EMPLOYEES[2],
    signInTime: new Date(new Date(now).setHours(9, 0, 0)).toISOString(),
    signOutTime: new Date(new Date(now).setHours(12, 30, 0)).toISOString(),
    status: 'signed_out',
    date: today,
    signInLocation: {
      latitude: 51.4545,
      longitude: -0.9781,
      accuracy: 18,
      capturedAt: new Date(new Date(now).setHours(9, 0, 0)).toISOString(),
    },
    signOutLocation: {
      latitude: 51.4546,
      longitude: -0.9783,
      accuracy: 15,
      capturedAt: new Date(new Date(now).setHours(12, 30, 0)).toISOString(),
    },
  },
  {
    _id: 'att-005',
    employee: MOCK_EMPLOYEES[1],
    signInTime: new Date(new Date(now).setHours(8, 0, 0)).toISOString(),
    signOutTime: new Date(new Date(now).setHours(16, 30, 0)).toISOString(),
    status: 'signed_out',
    date: today,
  },
  {
    _id: 'att-006',
    employee: MOCK_EMPLOYEES[4],
    signInTime: new Date(new Date(now).setHours(7, 30, 0)).toISOString(),
    signOutTime: new Date(new Date(now).setHours(15, 30, 0)).toISOString(),
    status: 'signed_out',
    date: today,
  },
  {
    _id: 'att-004',
    employee: MOCK_EMPLOYEES[3],
    signInTime: new Date(new Date(now).setHours(8, 30, 0)).toISOString(),
    status: 'signed_in',
    date: today,
  },
]
